### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by rastarr** [codebox/mosaic#16]
Hi, just d/l'd this for a test drive.
Every config is the default out of the box but I get the following errors:

`python3 /Volumes/SSD2/Users/martin/Downloads/_CleanShotX-Save/mosaic.py  2019-02-04--16-11-41.jpeg '/Volumes/Creation/Thai-beach'
Processing main image...
Main image processed.
Reading tiles from /Volumes/Creation/Thai-beach...
Processed 0 tiles.
Building mosaic, press Ctrl-C to abort...
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Volumes/SSD2/Users/martin/Downloads/_CleanShotX-Save/mosaic.py", line 169, in build_mosaic
    tile_data = all_tile_data_large[best_fit_tile_index]
TypeError: list indices must be integers or slices, not NoneType`

Any ideas? running on macOS Monterey 12.1. Python

**Comment by codebox** [comment]
It looks like the utility can't find your 'tile' images (in the error message it says Processed 0 tiles) it may be because of the single-quotes in the path to '...Thai-beach' try running the command without them and see if that helps

**Comment by rastarr** [comment]
Nope, same errors, weirdness-

`python3 /Volumes/SSD2/Users/martin/Downloads/_CleanShotX-Save/mosaic.py  2019-02-04--16-11-41.jpeg /Volumes/Creation/Thai-beach
Processing main image...
Main image processed.
Reading tiles from /Volumes/Creation/Thai-beach...
Processed 0 tiles.
Building mosaic, press Ctrl-C to abort...
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Volumes/SSD2/Users/martin/Downloads/_CleanShotX-Save/mosaic.py", line 169, in build_mosaic
    tile_data = all_tile_data_large[best_fit_tile_index]
TypeError: list indices must be integers or slices, not NoneType`

**Comment by codebox** [comment]
That's strange, it might be some permissions issue with the directory containing the tiles, maybe try copying them to the same volume as the code somewhere nice and accessible like a folder on your desktop

**Comment by rastarr** [comment]
Oh thanks so much. that did the trick.
Not sure why but can look at that later.
thanks again Rob
