### ISSUE TITLE
Playing with this and I got this odd error. 

### ISSUE THREAD

**Issue by notanark** [codebox/mosaic#2]
C:\code\sold>python driver.py flag.jpg Images
'python' is not recognized as an internal or external command,
operable program or batch file.

C:\code\sold>c:\Python27\python.exe driver.py flag.jpg Images
Reading tiles from 'Images'...
Processed 60 tiles.
Processing main image...
Main image processed.
Building mosaic, press Ctrl-C to abort...
Traceback (most recent call last):
Traceback (most recent call last):
  File "driver.py", line 234, in <module>
  File "<string>", line 1, in <module>
      File "c:\Python27\lib\multiprocessing\forking.py", line 381, in main
mosaic(sys.argv[1], sys.argv[2])
      File "driver.py", line 227, in mosaic
self = load(from_parent)
      File "c:\Python27\lib\pickle.py", line 1384, in load
compose(image_data, tiles_data)
  File "driver.py", line 199, in compose
    return Unpickler(file).load()
      File "c:\Python27\lib\pickle.py", line 864, in load
Process(target=build_mosaic, args=(result_queue, all_tile_data_large, original_img_large)).start()
    dispatch[key](self)
  File "c:\Python27\lib\multiprocessing\process.py", line 130, in start
  File "c:\Python27\lib\pickle.py", line 886, in load_eof
    self._popen = Popen(self)
  File "c:\Python27\lib\multiprocessing\forking.py", line 277, in __init__
    raise EOFError
    EOFErrordump(process_obj, to_child, HIGHEST_PROTOCOL)

  File "c:\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "c:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "c:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "c:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "c:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "c:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "c:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\Python27\lib\pickle.py", line 554, in save_tuple
    save(element)
  File "c:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\Python27\lib\pickle.py", line 731, in save_inst
    save(stuff)
  File "c:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "c:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "c:\Python27\lib\pickle.py", line 313, in save
    (t.__name__, obj))
pickle.PicklingError: Can't pickle 'ImagingCore' object: <ImagingCore object at 0x02F74830>

**Comment by codebox** [comment]
I suspect this issue is similar to the one described in [this StackOverflow post](http://stackoverflow.com/questions/9670926/multiprocessing-on-windows-breaks), I don't have a fix at the moment but would be happy to accept a patch if anyone wants to investigate
